language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

arch:
  - amd64
  - arm64

cache: apt

compiler:
  - gcc

os: linux

addons:
  apt:
    packages:
      - libsystemd-dev

script:
  - pip wheel cysystemd -w dist

deploy:
  provider: releases
  api_key:
    secure: Ate65raP7lk7m4/a0c7shr+yEvdnnojar6dWirKYGvlGjstF1XOSpWfHA3wLOSWZhKnsGZxt+g1IUAePtdGXhYK4/hLXJ8fbnfl7fU2zxBuUFCpkJ0KpXRmRZV8fp2/y804sYLvmkOi3kqOEAVmNW6MbQq+/OVVXfcxYPDEytoDG5hdSuNohTcKK9GyZ3LjFDdXqeBzwG09YQpMf/NIamMJROPNOzso9ni4d6XjpFdNCn6TGMp+x62loakN6Wfhfq4uddmdLpVUCnG0wLcUtmjDPjK9orPc2YPDsth/bMgOeAsdZAHXqsXb0tR0jRaYv/267kvR7yOAz75ZMGph8b48P0DJgOL2hJ8o1+8Gc7mK+WD9y4dMONO+wi8VFtCBecpLviuI7y0htmwfpx478IZUPqz13HK/m0edYfI8Ujt+qA/NJ2ERs5KUGfQBUetV+qpm/AyKRxlzOhgp48oTLEpPET5Agoqrwibb7NP36Gdh8NyzNVjAfht9MV/kP8ECxFWgTdqzXFzYI4LJkg9tbTIl8tpcU7zDmeHPVwtXy6TwP38ODmV0A9T7OWBIivB1x6aNeYwjQNHOZICnONYqwATWyg6briNeU+9uGubZyFdLUySIE4bdMXjVB7mjL+3hb5wy8ROapZ34DOkmY/mZ14urQi9Ekk5ewfyq8a/EiaoU=
  file: dist/*.whl
  skip_cleanup: true
  on:
    tags: true
